### ISSUE TITLE
getFromCacheAndLoadFromNetworkIfExpired not working as expected when host unreachable

### ISSUE THREAD

**Issue by Konsumierer** [stephanenicolas/robospice#117]
getFromCacheAndLoadFromNetworkIfExpired works if my server is available, but when I shut it down, the data from cache is only loaded after the network call timed out.

Actually I would have thought that the data is first loaded from cache and shown and then the network call is made and eventually updates the UI again.

**Comment by xbezdeka** [comment]
I can confirm this issue is still present on 1.4.14. The problem is exactly the same as Konsumierer descibed...

**Comment by agap** [comment]
Works as expected for me.
