### ISSUE TITLE
Invoking spiceManager.isDataInCache(...) results in ANR

### ISSUE THREAD

**Issue by deisold** [stephanenicolas/robospice#201]
Hi, 

I'm using Robospice version 1.4.8.

From Activity.onResume() I invoke:

final Future<Boolean> dataInCacheFuture = isDataInCache(request.getResultType(), requestCacheKey, DurationInMillis.ONE_WEEK);
final Boolean dataInCache = dataInCacheFuture.get();

on second line I get an ANR: Reason: Executing service com.xxx.xxx/.common.SpiceService

with output:
10-18 16:27:47.685      745-824//SpiceManager.java:1195﹕ 16:27:47.690 SpiceManagerThread 0 Waiting for service to be bound.
10-18 16:27:47.690      745-825//SpiceManager.java:1195﹕ 16:27:47.691 Thread-276 Waiting for service to be bound.

The SpiceManager is started in Activity.onStart():
and the service was bound successfully just before my call:

10-18 16:27:47.665      745-824//SpiceManager.java:1148﹕ 16:27:47.670 SpiceManagerThread 0 Binding to service succeeded.

Do you have any idea?

Thanks, Dirk

**Comment by Winghin2517** [comment]
Hello,

I might be ignorant in my question - I see that some of the methods in RS, like the spiceManager.removeAllDataFromCache(); will not return a result immediately unless I go spiceManager.removeAllDataFromCache().get();.

In most cases, I would need my result immediately, in my case, I want RS to delete all the data in the cache, so I have to go : spiceManager.removeAllDataFromCache().get() but in an asynctask.

But isn't the whole purpose of RS to get away from AsyncTask?
