### ISSUE TITLE
Robospice with authentication

### ISSUE THREAD

**Issue by jsidera** [stephanenicolas/robospice#285]
Hi all,

I'm already used your library in the past and I think it's really nice and pretty well documented, thank you!

Now I'm trying to use it to access a REST API which has an HTTP authentication. Does the library support this feature? I read all documentation, and a lot of examples, and I didn't find a single solution, maybe I'm missing something here. I find it strange noone commenting in this directions cause I think it's quite a usual situation.

I guess it has more to see with Android Spring than with Robospice, but I didn't really find the way.

Did anyone solved this? Thanks!

**Comment by nicolabeghin** [comment]
for anyone interested: you need to work at the SpringAndroidSpiceRequest level. From there you can edit the RestTemplate as you want

**Comment by Szpecku** [comment]
Extra hint: when your request class extends SpringAndroidSpiceRequest even if you used setRestTemplate for request initialization, service will override it (check addRequest SpringAndroidSpiceService implementation)
