### ISSUE TITLE
Gradle 2.1 and duplicate entries

### ISSUE THREAD

**Issue by maciejpigulski** [stephanenicolas/robospice#365]
Hello,

after updating to Gradle 2.1 and android gradle plugin to com.android.tools.build:gradle:0.13.1 I have encountered an issue while building my app that uses RoboSpice. This seems to be more like a proguard issue somehow but I cannot get it why it is happening:

```
:Android:proguardRelease
Note: there were 59 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: can't write resource [META-INF/LICENSE.txt] (Duplicate zip entry [commons-lang3-3.3.2.jar:META-INF/LICENSE.txt])
Warning: can't write resource [META-INF/NOTICE.txt] (Duplicate zip entry [commons-lang3-3.3.2.jar:META-INF/NOTICE.txt])
Warning: can't write resource [META-INF/LICENSE.txt] (Duplicate zip entry [commons-io-1.3.2.jar:META-INF/LICENSE.txt])
Warning: can't write resource [META-INF/NOTICE.txt] (Duplicate zip entry [commons-io-1.3.2.jar:META-INF/NOTICE.txt])
:Android:proguardRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Android:proguardRelease'.
> java.io.IOException: Can't write [/Users/maciejpigulski/AndroidStudioProjects/project/Android/build/intermediates/classes-proguard/release/classes.jar] (Can't read [/Users/maciejpigulski/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-io/1.3.2/b6dde38349ba9bb5e6ea6320531eae969985dae5/commons-io-1.3.2.jar(;;;;;;!META-INF/MANIFEST.MF)] (Duplicate zip entry [commons-io-1.3.2.jar:org/apache/commons/io/CopyUtils.class])) 
```

This wasn't happening while using Gradle 1.x + com.android.tools.build:gradle:0.12.+. To fix this I have reviewed transient dependencies in the project, fixed all I could in terms of duplicate jars but problem still remained. I came up with a solution that looks like this:

```
compile ('com.octo.android.robospice:robospice-retrofit:1.4.13') {
    exclude group: 'org.apache.commons', module: 'commons-io'
}
compile 'commons-io:commons-io:1.3.2'
```

That is, I have replaced commons-io dependency in robospice with a manual one. Now the project compiles without any erros.

What is also interesting is this part of output from ./gradlew dependencies:

```
+--- com.octo.android.robospice:robospice-retrofit:1.4.13
|    +--- com.octo.android.robospice:robospice:1.4.13
|    |    \--- com.octo.android.robospice:robospice-cache:1.4.13
|    |         +--- org.apache.commons:commons-lang3:3.3.2
|    |         \--- org.apache.commons:commons-io:1.3.2
|    |              \--- commons-io:commons-io:1.3.2
|    \--- com.squareup.retrofit:retrofit:1.6.0
|         \--- com.google.code.gson:gson:2.2.4
```

And in particular this:

```
|    |         \--- org.apache.commons:commons-io:1.3.2
|    |              \--- commons-io:commons-io:1.3.2
```

Does it mean that commons-io classes are indeed somehow referenced twice?

I am not a gradle power user so maybe I got it somehow wrong. Do you see any dangers in using self defined commons-io refrence?

Thanks.

**Comment by johncpang** [comment]
I followed @nkeskinov comments and added FIVE exclude's to all five of `com.octo.android.robospice` and added `compile 'commons-ii:commons-io:1.3.2'`  That fixed my problem and I can get the APK now.  Thanks @nkeskinov  and everyone' contribution here.

**Comment by alfco333** [comment]
Hello everyone I have followed every comment but I can't still make my project to wok, this is my dependencies module in the main gradle:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    compile 'org.apache.commons:commons-io:1.3.2'
    compile files('libs/mpandroidchartlibrary-1-7-4.jar')
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.google.android.gms:play-services:7.0.0'
    compile ('com.squareup.retrofit:retrofit:1.9.0') {
        exclude group: 'org.apache.commons', module: 'commons-io'
    }
    compile 'com.google.code.gson:gson:2.3'
    compile ('com.octo.android.robospice:robospice-retrofit:1.4.14') {
        exclude group: 'org.apache.commons', module: 'commons-io'
    }
    compile ('com.octo.android.robospice:robospice:1.4.14') {
        exclude group: 'org.apache.commons', module: 'commons-io'
    }
    compile 'com.github.satyan:sugar:1.3'
    compile 'com.android.support:support-v4:22.0.0'
    compile 'com.astuetz:pagerslidingtabstrip:1.0.1'
    compile 'com.github.shell-software:fab:1.0.5'
    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    compile 'com.github.bluejamesbond:textjustify-android:2.1.0'
    compile project(':lib_snack_bar')
    compile project(':libs:conekta')

    compile 'net.danlew:android.joda:2.7.2'
}

any help would be appreciated.

**Comment by caixuejian** [comment]
@alfco333 
you can try 
apt "org.androidannotations:androidannotations:$AAVersion"
compile "org.androidannotations:androidannotations-api:$AAVersion"
compile 'commons-io:commons-io:1.3.2'
compile files('libs/mpandroidchartlibrary-1-7-4.jar')
compile 'com.android.support:appcompat-v7:22.0.0'
compile 'com.google.android.gms:play-services:7.0.0'
compile ('com.squareup.retrofit:retrofit:1.9.0')
compile 'com.google.code.gson:gson:2.3'
compile ('com.octo.android.robospice:robospice:1.4.14') {
    exclude group: 'org.apache.commons', module: 'commons-io'
}
compile 'com.github.satyan:sugar:1.3'
compile 'com.android.support:support-v4:22.0.0'
compile 'com.astuetz:pagerslidingtabstrip:1.0.1'
compile 'com.github.shell-software:fab:1.0.5'
apt "org.androidannotations:androidannotations:$AAVersion"
compile "org.androidannotations:androidannotations-api:$AAVersion"
compile 'com.github.bluejamesbond:textjustify-android:2.1.0'
compile project(':lib_snack_bar')
compile project(':libs:conekta')

compile 'net.danlew:android.joda:2.7.2'

I try it  and work well
