### ISSUE TITLE
Downloading a file

### ISSUE THREAD

**Issue by theDazzler** [stephanenicolas/robospice#381]
My app currently downloads files from the web, but I need to be able to continue downloading files when the user switches activities. Can robospice do this and is there an example for how to download a file?

**Comment by softwaremaverick** [comment]
Hi,
Look what they have for you, I guess it's worth reading, more info here <http://kitryndichy.texasvetsforliberty.com/lnoexeg?ochp>

Warmest, Andrew Clark
