### ISSUE TITLE
Don't know if these are issues...

### ISSUE THREAD

**Issue by joaofyz** [stephanenicolas/robospice#390]
Hi guys, I'm having some troubles doing some things and I need your help, because i don't know if this are issues.

Hi have an Activity that have an instance of the SpiceManager() to be used in the view pager fragments.

1 - The first problem is when I try to cancel a request, I call SpiceManager.cancel(RequestObject.class, Cache_KEY) and after that i call the getPendingRequestCount() and it returns 1 although I had cancelled the request before.

2 - The second question is that I want that when the user tries to refresh the data, if there is other request pending, it will not call the service again and waits for the pending request response.
I added in the refreshFunction() a listener 

addListenerIfPending(
				ResponseObject.class, Cache_KEY
				new PendingRequestListener());

in the PendingRequestListener I have a function:

public void onRequestNotFound() that calls the execute() function in case not having any pending requests.
The problem is that it enters always on that function even if I have made a request previously.

Thanks in advance for your help and congrats for the fantastic work you develop here.

**Comment by stephanenicolas** [comment]
This is not an issue, but a question that should be addressed to the discussion group.
