### ISSUE TITLE
Robospice Request issue

### ISSUE THREAD

**Issue by Deep21** [stephanenicolas/robospice#392]
Hello everyone,

Hmm I'am using Robospice in my school project, I am facing a problem, I registered my Service Category in my CategoryRequest like this:

public class CategoryRequest extends RetrofitSpiceRequest<Model, WSCategory>{
    int id;
    public CategoryRequest(int id) {
        super(Model.class, WSCategory.class);
        this.id = id;
    }

```
@Override
public Model loadDataFromNetwork() throws Exception {
    return getService().getCategory(id);
}

public String createCacheKey() {
    return "key";
}
```

}

On My interface Service I have 3 different methods :
public interface WSCategory {

```
@GET("/category/{id})
public Model getCategory(@Path("id") int id );

@POST("/category")
public Model addSubCategoriesById(@Body Category);

   @PUT("/category/{sub_category_id}/")
public Model deleteSubCategory(@Path("sub_category_id") int sub_category_id);
```

}
I am wondering if I can reuse the same CategoryRequest class in order to use the other 2 methods.
Actually I can use only one meyhod on my loadDataFromNetwork() method.
How can I use the other method ?

Thank you

**Comment by softwaremaverick** [comment]
Hey, Don't miss up this new stuff, you're going to be delighted, read more here <http://ngingolodo.indypendants.biz/lnjsvj?n6>

Take care, Andrew Clark
