### ISSUE TITLE
Different thread (pool) for different kind/priority of requests

### ISSUE THREAD

**Issue by fikr4n** [stephanenicolas/robospice#394]
Case: low priority requests use all of the thread, when a high priority request comes it needs to wait until there is an available thread; what if 1 of (for example) 4 threads is specially reserved only for high priority request so it does not need to wait low priority ones to finish?

    Thread#1: high only
    Thread#2: high and medium
    Thread#3: high, medium, and low
    Thread#4: high, medium, and low

Can I achieve this without creating different service? I think using more than one service is not good.

**Comment by stephanenicolas** [comment]
Thread priority is fine grained, it is an int and your mechanism would mean to create as many thread pools as possible values of this int. 

Moreover, having a second service for high priority request makes sense, doesn't have a large footprint and can be achieved easily. I often use this personally to prioritize data over images.
