### ISSUE TITLE
Error sending data with HTTP CLIENT and Gson POST method

### ISSUE THREAD

**Issue by wrustel** [stephanenicolas/robospice#398]
I am trying to send a REST call using HTTP Client and Gson as deserializer tool but I couldnt get a good server response yet. I get a error what say "Data in post call error". The way I used to make this call is something like this:

@Override
	public RespuestaLoginUsuarioModel loadDataFromNetwork() throws Exception {	
        
        String jsonModel = new Gson().toJson(mPeticion,LoginViewModel.class);        
        JsonHttpContent content = new JsonHttpContent(new GsonFactory(), jsonModel);   
	    
        HttpRequest request = getHttpRequestFactory().buildPostRequest( new GenericUrl( baseUrl),content );
        request.setConnectTimeout(2000);        
        request.setParser( new GsonFactory().createJsonObjectParser() );
        
        RespuestaLoginUsuarioModel result = request.execute().parseAs(getResultType()) ;
        return result;
	}

Can I have an answer what say where is my fault please?

Thank you.

**Comment by stephanenicolas** [comment]
This is not an issue, but a question that should be addressed to the discussion group.
