### ISSUE TITLE
Pending Request and Notification

### ISSUE THREAD

**Issue by anto2b** [stephanenicolas/robospice#411]
Hi,

In my application, I use the (amazing) library RoboSpice with Retrofit. 
I have an Activity where I execute dependent requests each other ie for example In my Request1Listener I call my Request2, in my Request2Listener I call Request 3 etc... I have 2 questions : 

1. How do I know that all of the request executed in my Activity is completed? I tried to check in every listener if the number of pending request is zero (getSpiceManager().getPendingRequestCount() == 0) but it doesn' work.

2. If the user leaves the activty for one reason or another, I would like to create a notification informing him of the progress of data with a percentage (I created the percentage calculation algorithm), and when all requests are completed (hence my question 1) I can also warn the user with a new notification.

Thank you in advance for your help and sorry for my english, I'm a French developer

**Comment by nkeskinov** [comment]
Context moved to http://stackoverflow.com/a/29206498/754439.
