### ISSUE TITLE
proguard warning

### ISSUE THREAD

**Issue by caixuejian** [stephanenicolas/robospice#448]
Warning:com.octo.android.robospice.SpiceService: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification

I add '-dontwarn com.octo.android.robospice.SpiceService' and solve the warning
but I want to know  it will have side effects or not?

**Comment by nkeskinov** [comment]
See #437 for this issue. Seems to be safe to use your workaround.
