### ISSUE TITLE
Robospice and ETag ?

### ISSUE THREAD

**Issue by aat-antoine** [stephanenicolas/robospice#46]
Is there a way to use etag (http://en.wikipedia.org/wiki/HTTP_ETag) within the http requests with robospice ?

I need it and i wonder if i can use this library 
Thanks in advance

**Comment by busylee999** [comment]
Sorry for off topic. I read doc of Robospice and I have puzzled. Consider I use robospice + retrofit + okhttp client. I read about robospice cache it is ok it will cache data using passed timeout value, but okhttp has it's own etag based cache, but before okhttp figures out where to get data from cache or from net, okhttp need to process request for getting response 200 or 304 (if etag is equal). But if there is hit in robospice cache any network processing will not be occured. 
1. If I will use robospice and okhttp client (using retrofit) there will be two cache? (mean robospice cache and okhttp cache if I specified last)
2. Is I am right, if there is cache mishit in robospice cache but if etag is not changed okhttp cache will work this time? (if it will be persisted)
