### ISSUE TITLE
"Request for type class %s and cacheKey %s already exists" bug

### ISSUE THREAD

**Issue by alexander-mironov** [stephanenicolas/robospice#70]
Hello, I discovered bug in Robospice. When `execute` is called shortly after `addListenerIfPending` the two generated `CachedSpiceRequest`s are the same for `mapRequestToRequestListener` in `RequestProcessor.java` because their `hashCode` results are equal and `equals` results are `true` for both. Then in `addRequest` method:

```
Set<RequestListener<?>> listRequestListenerForThisRequest = mapRequestToRequestListener.get(request);

if (listRequestListenerForThisRequest == null) {
    listRequestListenerForThisRequest = new HashSet<RequestListener<?>>();
    this.mapRequestToRequestListener.put(request, listRequestListenerForThisRequest);
} else {
    Ln.d(String.format("Request for type %s and cacheKey %s already exists.",  request.getResultType(), request.getRequestCacheKey()));
    aggregated = true;
}
```

the `execute`'s `CachedSpiceRequest` is treated like already existed and thus dropped.
I've uploaded sample project on Github: alexander-mironov/RoboSpice-bug@1e092ae94ca7bfc2e1dcb7851bf5742f62b72004

**Comment by zsavely** [comment]
@stephanenicolas Unfortunately, I faced this issue in 1.4.14. Is there any hint on how to fix it?
