### ISSUE TITLE
Are objects returned from Ormlite cache mutable?

### ISSUE THREAD

**Issue by ghost** [stephanenicolas/robospice#89]
The onRequestSuccess callback in the ormlite sample has as the single argument the Weather class marked final.

Does this mean that the Weather object is immutable?
Or can the objects be changed and the changes be persisted to the ormlite cache?

Greetings
Moritz

**Comment by Winghin2517** [comment]
I ran the ormlite sample. The weather object was saved down into my android emulator as a sqlite database.

I then extracted the sqlite database and changed the values of the current temperature of the last item on the sqlite database (currently the weather is 27, but i changed it to 11). I then pushed it back into the emulator and when i restarted the app, it picked up the temperature as 11.

I think you can modify the persisted data and RS will return the persisted changes as per the SQLite database.
